apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeName: etri-1
      containers:
      - name: tango-mariadb
        image: mariadb:10
        resources:
          limits:
            cpu: 500m
            memory: 2048Mi
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: confvol
          mountPath: /etc/mysql
          subPath: my.cnf
        - name: mysqlvol
          mountPath: /var/lib/mysql
        - name: testvol
          mountPath: /docker-entrypoint-initdb.d/
        env:
        - name: MARAIDB_DATABASE
          value: labelling
        - name: MARAIDB_USER
          value: username
        - name: MARAIDB_PASSWORD
          value: password
        - name: MARIADB_ROOT_PASSWORD
          value: password

      volumes:
        - name: confvol
          persistentVolumeClaim:
            claimName: pvcnfs-mariadb-conf
        - name: mysqlvol
          persistentVolumeClaim:
            claimName: pvcnfs-mariadb-mysql
        - name: testvol
          persistentVolumeClaim:
            claimName: pvcnfs-mariadb-test
            
---

apiVersion: v1
kind: Service
metadata:
  name: mariadbservice
spec:
  selector:
    app: mariadb
  # type : NodePort
  ports:
  # - nodePort: 8181
  - port: 3306
    targetPort: 3306
    name: maria