apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcnfs-autonnnk
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  selector:
    matchLabels:
      name: autonnnk
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfs-autonnnk
  labels:
    name: autonnnk
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/etri-1/TANGO/autonn/neck_nas


  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /home/etri-1/TANGO/autonn/neck_nas
  #   server: 192.168.0.181
    
