apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfs-bms
  labels:
    name: bms
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/etri-1/TANGO/base_model_select
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /home/etri-1/TANGO/base_model_select
  #   server: 192.168.0.181

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcnfs-bms
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  selector:
    matchLabels:
      name: bms
  accessModes:
    - ReadWriteMany

