apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcnfs-prm
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  selector:
    matchLabels:
      name: prm
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfs-prm
  labels:
    name: prm
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/etri-1/TANGO/project_manager
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /home/etri-1/TANGO/project_manager
  #   server: 192.168.0.181
    
